seq_length: 22
em_drop: 0.2
fc_drop: 0.4
initializer: he_uniform # lecun_uniform, normal, he_normal, he_uniform
em_dim: 44
rnn_units: 60
fc_num_hidden_layers: 3
fc_num_units: 320
fc_activation: elu # elu, relu, tanh, sigmoid, hard_sigmoid
ext1_up: 50
ext1_down: 13
ext2_up: 13
ext2_down: 50