train:
  # output_dir:
  # trial_name:
  batch_size: 100
  num_epochs: 33
  last_epoch: -1
  clip_value: 1.0
  accumulate_steps: 1
  device: cuda # cuda, cpu

# train components
initializer:
  name: kaiming_uniform_ # uniform_, normal_, xavier_uniform_, xavier_normal_, kaiming_uniform_, kaiming_normal_, trunc_normal_

optimizer:
  name: AdamW # Adadelta, Adafactor, Adagrad, Adam, AdamW, Adamax, ASGD, NAdam, RAdam, RMSprop, SGD
  learning_rate: 0.0001
  weight_decay: 0.0

lr_scheduler:
  name: CosineAnnealingWarmRestarts # CosineAnnealingWarmRestarts, ConstantLR, ReduceLROnPlateau
  warmup_epochs: 3
  period_epochs: 30

dataset:
  data_file: AI/dataset/dataset.json.gz
  # name: # SX_spcas9, SX_spymac, SX_ispymac
  test_ratio: 0.05
  validation_ratio: 0.05
  random_insert_uplimit: 0
  insert_uplimit: 2
  seed: 63036

# utils
generator:
  seed: 63036

logger:
  log_level: WARNING # CRITICAL, FATAL, ERROR, WARNING, INFO, DEBUG, NOTSET

metric:
  - class_path: AI.preprocess.metric.CrossEntropy
    init_args:
      ext1_up: 25
      ext1_down: 6
      ext2_up: 6
      ext2_down: 25
  - class_path: AI.preprocess.metric.NonZeroCrossEntropy
    init_args:
      ext1_up: 25
      ext1_down: 6
      ext2_up: 6
      ext2_down: 25
  - class_path: AI.preprocess.metric.NonWildTypeCrossEntropy
    init_args:
      ext1_up: 25
      ext1_down: 6
      ext2_up: 6
      ext2_down: 25
  - class_path: AI.preprocess.metric.NonZeroNonWildTypeCrossEntropy
    init_args:
      ext1_up: 25
      ext1_down: 6
      ext2_up: 6
      ext2_down: 25

  - class_path: AI.preprocess.metric.GreatestCommonCrossEntropy
    init_args:
      ext1_up: 25
      ext1_down: 6
      ext2_up: 6
      ext2_down: 25
