class_path: AI.preprocess.DeepHF.model.XGBoostConfig
init_args:
  ext1_up: 25
  ext1_down: 6
  ext2_up: 6
  ext2_down: 25
  learning_rate: 0.05
  subsample: 0.1
  colsample_bytree: 0.3
  max_depth: 6
  reg_lambda: 700
  nthread: 16
  booster: dart # gbtree, gblinear, dart
  num_boost_round: 100
  early_stopping_rounds: 10
