max_micro_homology: 7
loss_weights:
  reverse_sample_negative_ELBO: 1.0
  non_sample_CE: 1.0
    parser_CRISPR_diffuser.add_argument("--MCMC_corrector_factor", nargs='+', type=float, default=[1., 0., 0.001], help="weight of the MCMC corrector term")
    parser_CRISPR_diffuser.add_argument("--unet_channels", nargs='+', type=int, default=[32, 64, 96, 64, 32], help="the output channels of Unet")
    parser_CRISPR_diffuser.add_argument("--noise_scheduler", type=str, default="exp", choices=["linear", "cosine", "exp", "uniform"], help="noise scheduler used for diffuser model")
    parser_CRISPR_diffuser.add_argument("--noise_timesteps", type=int, default=20, help="number of noise scheduler time steps")
    parser_CRISPR_diffuser.add_argument("--cosine_factor", type=float, default=0.008, help="parameter control cosine noise scheduler")
    parser_CRISPR_diffuser.add_argument("--exp_scale", type=float, default=5.0, help="scale factor of exponential noise scheduler")
    parser_CRISPR_diffuser.add_argument("--exp_base", type=float, default=5.0, help="base parameter of exponential noise scheduler")
    parser_CRISPR_diffuser.add_argument("--uniform_scale", type=float, default=1.0, help="scale parameter for uniform scheduler")
    parser_CRISPR_diffuser.add_argument("--display_scale_factor", type=float, default=0.1, help="exponential scale of the distribution image")